/** Indicate graph type. */
export enum GraphTypeName {
    STAFF_STATISTICS = 'STAFF_STATISTICS',
    TRAINEE_STATISTICS = 'TRAINEE_STATISTICS',
    COVERAGE_STATISTICS = 'FULL_TIME_TEACHER_TRAINED_COVERAGE',
    HOURS_STATISTICS = 'TRAINING_HOURS_WORKLOAD_STATISTICS',
}
