/** Indicate graph type. */
export enum GraphTypeName {
    TEACHERS_STATISTICS = 'TEACHERS_STATISTICS',
    TRAINEE_STATISTICS = 'TRAINEE_STATISTICS',
    COVERAGE_STATISTICS = 'COVERAGE_STATISTICS',
    HOURS_STATISTICS = 'TRAINING_HOURS_STATISTICS',
}
