/** Indicate the status of a Record. */
export enum RecordStatus {
  STATUS_PRESUBMIT = 0,
  STATUS_SUBMITTED = 1,
  STATUS_FACULTY_ADMIN_REVIEWED = 2,
  STATUS_SCHOOL_ADMIN_REVIEWED = 3,
  STATUS_FEEDBACK_REQUIRED = 4,
  STATUS_FEEDBACK_SUBMITED = 5,
  STATUS_DEPARTMENT_ADMIN_REJECTED = 6,
  STATUS_SCHOOL_ADMIN_REJECTED = 7,
  STATUS_CLOSED = 8
}

