/** Indicate the status of a Record. */
export enum RecordStatus {
  STATUS_PRESUBMIT = 0,
  STATUS_SUBMITTED = 1,
  STATUS_FACULTY_ADMIN_REVIEWED = 2,
  STATUS_SCHOOL_ADMIN_REVIEWED = 3,
  STATUS_WITHOUT_FEEDBACK = 4,
  STATUS_WITH_FEEDBACK = 5
}

